### ISSUE TITLE
duckduckgo search bar background-color change?

### ISSUE THREAD

**Issue by cyckl** [cyckl/luna#2]
Been wondering if we could change the background of the search bar itself to # 393F4C because the search bar maker didn't let me do that

```
https://duckduckgo.com/search.html?width=400&prefill=ROT Search&_bgcolor=#393F4C_&focus=yes
```

**Comment by Incrested** [comment]
This should fix it: <iframe src="https://duckduckgo.com/search.html?width=400&prefill=ROT Search&focus=yes" style="overflow:hidden;margin:0;padding:0;width:458px;height:40px;" frameborder="0"></iframe>

**Comment by doamatto** [comment]
Added in pull request #13
